version: "~> 1.0"
sudo: true
dist: bionic
language: node_js
node_js: 13
branches:
  only:
    - master
    - dev
cache: yarn
install:
  - yarn install
  - yarn global add codecov
script:
  - yarn lint
  - yarn test:coverage
  - codecov
